from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime
import uuid

class AgentRegistrationPayload(BaseModel):
    instance_id: uuid.UUID
    instance_name: str
    cloud_provider: str
    agent_api_key: str = Field(..., description="The API key generated by the agent, to be stored by the server")

class CPUMetrics(BaseModel):
    usage_percent: float
    core_count: int
    per_core_usage: List[float]

class MemoryMetrics(BaseModel):
    total_memory: int
    used_memory: int
    available_memory: int
    total_swap: int
    used_swap: int

class DiskMetric(BaseModel):
    name: str
    mount_point: str
    total_space: int
    available_space: int
    filesystem: str
    total_written_bytes: int
    total_read_bytes: int

class NetworkMetric(BaseModel):
    interface_name: str
    received_bytes_total: int
    transmitted_bytes_total: int

class SystemInfo(BaseModel):
    hostname: str
    os_name: str
    os_version: str
    kernel_version: str
    uptime: int

class SystemMetricsPayload(BaseModel):
    timestamp: datetime
    instance_id: uuid.UUID
    cpu_metrics: CPUMetrics
    memory_metrics: MemoryMetrics
    disk_metrics: List[DiskMetric]
    network_metrics: List[NetworkMetric]
    system_info: SystemInfo

class MetricsBatchWrapper(BaseModel):
    metrics: List[SystemMetricsPayload]

class HeartbeatPayload(BaseModel):
    instance_id: uuid.UUID

class AgentRegistrationResponse(BaseModel):
    message: str
    instance_id: uuid.UUID

class MessageResponse(BaseModel):
    message: str

class HealthResponse(BaseModel):
    status: str
    message: str
    timestamp: datetime

class StoredAgent(BaseModel):
    instance_id: uuid.UUID
    instance_name: str
    cloud_provider: str
    agent_api_key: str
    registered_at: datetime
    last_heartbeat_at: Optional[datetime] = None

class StoredMetricsBatch(BaseModel):
    received_at: datetime
    instance_id: uuid.UUID
    metrics: List[SystemMetricsPayload]